-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")

-- Bezier curves
hl.curve("superSnappy", { type = "bezier", points = { {0.1, 1.05}, {0.15, 1.05} } })

-- Animations
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.0,
    bezier = "superSnappy",
    style = "fade",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
