-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            enabled = false,
        },
    },
})

-- Bezier curves
hl.curve("superSnappy", { type = "bezier", points = { {0.1, 1.05}, {0.15, 1.05} } })

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4.0,
    bezier = "superSnappy",
    style = "slidefade 12%",
})
