[config]

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
# slap kitty awake
post_hook = "pkill -USR1 kitty 2>/dev/null || true"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch-colors.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.quickshell]
input_path = "~/.config/matugen/templates/Theme.qml"
output_path = "~/.config/quickshell/Theme.qml"


[templates.palette]
input_path = "~/.config/matugen/templates/palette.css"
output_path = "~/.config/quickshell/palette.css"

[templates.zsh]
input_path = "~/.config/matugen/templates/zsh-colors.zsh"
output_path = "~/.config/zsh/matugen.zsh"
# notify live zsh sessions
post_hook = "pkill -USR2 zsh 2>/dev/null || true"

# dump gtk4 palette into colors.css
[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4.css"
output_path = "~/.config/gtk-4.0/colors.css"

# dump gtk3 palette into colors.css and execute the double-tap
[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk3.css"
output_path = "~/.config/gtk-3.0/colors.css"
# terrorize both gtk versions simultaneously
post_hook = "$HOME/.config/matugen/post-hook-scripts/gtk-themes-reload.zsh 2>/dev/null || true"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim-colors.lua"
output_path = "~/.config/nvim/lua/config/colors.lua"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"
