barPosition="top"
barMargin=0
barFloating=false
barHeight=32
barStyle="regular"
scoopRadius=16
scoopTension=0.55228475
screenCornerRadius=16
screenBorderWidth=4
screenFrameDocked=true
screenCornerMode="all"
cornerStyle="cubic"
cornerColorMode="bar"
currentWallpaper="/home/ashley/.wallpapers/wallhaven/x6loqd.jpg"
matugenMode="light"
matugenScheme="scheme-tonal-spot"
awwwTransitionType="wipe"
awwwTransitionAngle=30
awwwTransitionStep=90
awwwTransitionDuration=3
awwwTransitionFps=60
awwwFilter="Lanczos3"
mpvPanscan=1
mpvAudio=false
dnd=false
vibeStyle="nerd"
animSpeed="hyprland"
unhingedFlavor=true
showWorkspaces=true
showWindowTitle=true
showClock=true
showBattery=true
showSystemTray=true
showVolume=true
showMedia=true
showNotifications=true
showLauncher=true
showPowerMenu=true
showNetwork=true
showBluetooth=true
showClipboard=true
showIdleInhibitor=true
showQuickSettings=true
showWallpaper=true
showQuickNotes=true
showMotionSandbox=false
showBarStudio=false
barModulesLeft='["launcher","wallpaper","workspaces","windowTitle"]'
barModulesCenter='["clock"]'
barModulesRight='["media","quickNotes","clipboard","idleInhibitor","notifications","systemTray","bluetooth","network","volume","battery","quickSettings","powerMenu"]'
iconSet="windows"
clockFormat="h:mm ap"
dateFormat="ddd, MMM d"
showBarDate=false
workspaceCount=10
fontFamily="Segoe UI Variable"
fontMono="Consolas"
fontWindows="Segoe Fluent Icons"
fontAwesome="Font Awesome 6 Free"
fontMaterial="Material Symbols Rounded"
fontScale=1
fontWeight="regular"
networkAliases='{}'
screenshotDir="~/Pictures/Screenshots"
screenshotDefaultAction="both"
screenshotWindowSnapping=true
screenshotNotify=true
screenshotFreeze=true
screenshotDimOpacity=0.45
screenshotBorderWidth=2
screenshotBorderRadius=4
screenshotShowCrosshair=true
screenshotShowBadge=true
screenshotShowHandles=true
screenshotFlash=false
barRadius=0
barOpacity=1
widgetRadius=2
popupRadius=8
widgetSpacing=4
widgetPaddingH=8
popupOpacity=1
volumeStep=5
volumeMax=100
clockShowSeconds=false
clockMilitary=true
notificationTimeout=5000