barPosition="top"
barMargin=0
barFloating=false
barHeight=32
barStyle="regular"
scoopRadius=10
scoopTension=0.55228475
screenCornerRadius=16
screenBorderWidth=2
screenFrameDocked=true
screenCornerMode="all"
cornerStyle="cubic"
cornerColorMode="bar"
currentWallpaper="/home/ashley/.wallpapers/wallhaven/4vkdo3.jpeg"
matugenMode="dark"
matugenScheme="scheme-tonal-spot"
awwwTransitionType="wave"
awwwTransitionAngle=120
awwwTransitionStep=90
awwwTransitionDuration=3
awwwTransitionFps=60
awwwFilter="Lanczos3"
mpvPanscan=1
mpvAudio=false
dnd=false
vibeStyle="nerd"
animSpeed="hyprland"
unhingedFlavor=false
showWorkspaces=true
showWindowTitle=true
showClock=true
showBattery=true
showSystemTray=true
showVolume=true
showMedia=true
showNotifications=true
showLauncher=true
showPowerMenu=true
showNetwork=true
showBluetooth=true
showClipboard=true
showIdleInhibitor=true
showQuickSettings=true
showWallpaper=true
showQuickNotes=true
showMotionSandbox=false
showBarStudio=false
barModulesLeft='["launcher","wallpaper","workspaces","windowTitle"]'
barModulesCenter='["clock"]'
barModulesRight='["media","quickNotes","clipboard","idleInhibitor","notifications","systemTray","bluetooth","network","volume","battery","quickSettings","powerMenu"]'
iconSet="material"
clockFormat="HH:mm:ss"
dateFormat="ddd, MMM d"
showBarDate=false
workspaceCount=10
fontFamily="Google Sans Flex"
fontMono="JetBrainsMono Nerd Font"
fontWindows="Segoe Fluent Icons"
fontAwesome="Font Awesome 6 Free"
fontScale=1
fontWeight="regular"
networkAliases='{}'