-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = false,
    },
    decoration = {
        blur = {
            enabled = false,
        },
    },
    general = {
        allow_tearing = false,
        layout = "dwindle",
    },
})
