$primary = rgb(d0bcff)
$primary_container = rgb(4f378b)
$on_primary = rgb(381e72)
$surface = rgb(141218)
$surface_container_high = rgb(2b2930)
$on_surface = rgb(e6e1e5)
$on_surface_variant = rgb(cac4d0)
$error = rgb(f2b8b5)
$outline = rgb(938f99)
