# the manifesto of a recovering arch refugee who ran aur malware on bare metal
# and fled to functional programming to escape the consequences of mutable state.

{ config, pkgs, ... }:

{
  imports =
    [ # hardware autopsy generated by nixos-generate-config
      ./hardware-configuration.nix
    ];

  # --- 1. bootloader & boot graphics (richard nixon containment unit) ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # plymouth bgrt: hiding the crimes of the linux kernel behind an oem logo
  boot.plymouth = {
    enable = true;
    theme = "bgrt";
  };

  # gag the kernel so dmesg doesn't ruin the aesthetic illusion
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
    "quiet"
    "splash"
    "boot.shell_on_fail"
    "loglevel=3"
    "rd.systemd.show_status=false"
    "rd.udev.log_level=3"
    "udev.log_priority=3"
  ];

  # --- 2. networking & identity crisis ---
  networking.hostName = "lost"; # accurate description of user and system
  networking.networkmanager.enable = true;

  # --- 3. chronobiology & local lies ---
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # --- 4. display manager & bloatware fallback ---
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true; # emotional support desktop for when hyprland breaks

  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # --- 5. the tiling window manager held together by spite ---
  programs.hyprland = {
    enable = true;
    withUWSM = true; # systemd babysits the compositor so it doesn't fork into the abyss
  };

  # --- 6. audio plumbing & wireless suffering ---
  services.printing.enable = true;
  services.pulseaudio.enable = false; # kill pulseaudio with fire
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };
  hardware.bluetooth.enable = true;

  # --- 7. user definition (the person who ran atomic-lockfile) ---
  users.users."ashley" = {
    isNormalUser = true;
    description = "ashley";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" ];
    shell = pkgs.zsh;
    packages = with pkgs; [
      kdePackages.kate
    ];
  };

  # --- 8. shells, browsers, and experimental hubris ---
  programs.firefox.enable = true;
  programs.zsh.enable = true;
  programs.nix-ld.enable = true; # lets dynamically linked mason binaries & language servers run
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # --- 9. software hoarder collection ---
  environment.systemPackages = with pkgs; [
    # wayland rice tooling
    kitty
    git
    quickshell
    matugen
    awww
    mpvpaper
    hyprpicker
    wl-clipboard
    brightnessctl
    playerctl

    # cli toys to make the terminal look like a movie hacker scene
    micro
    neovim
    fastfetch
    eza
    zoxide
    fzf
    bat
    ripgrep
    fd
    jq
    yazi

    # portal glue code & python dependencies
    # (xdg-desktop-portal-hyprland is handled automatically by programs.hyprland)
    xdg-desktop-portal-gtk
    python3
    python3Packages.pillow

    # archive extraction
    unar
  ];

  # --- 10. typography (preventing status bar tofu rectangles) ---
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    material-symbols
    font-awesome
  ];

  # do not change this value or richard nixon crawls out of /nix/store
  # to personally revoke your root privileges and format your swap partition.
  system.stateVersion = "26.05";
}
