# manifesto of a recovering arch refugee whose getdents64 syscall got hooked by an orphaned pkgbuild
# fleeing directly into functional isolation so npm install atomic-lockfile can never touch bare metal again.

{ config, pkgs, ... }:

{
  imports =
    [ # hardware autopsy autogenerated by nixos-generate-config so we know which silicon we are abusing
      ./hardware-configuration.nix
    ];

  # 1. bootloader & boot graphics: masking the sins of the kernel behind an oem logo
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.extraEntries = {
    "windows.conf" = ''
      title Windows 11
      efi /EFI/Microsoft/Boot/bootmgfw.efi
      sort-key 99_windows
    '';
  };
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 5; # timeout in seconds so you can choose Windows Boot Manager
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # plymouth bgrt: visual lobotomy so we don't have to watch acpi error traces flash across the screen
  boot.plymouth = {
    enable = true;
    theme = "bgrt";
  };

  # muzzle dmesg into absolute silence because ignorance is the only true form of stability
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;
  boot.kernelParams = [
    "quiet"
    "splash"
    "boot.shell_on_fail"
    "loglevel=3"
    "rd.systemd.show_status=false"
    "rd.udev.log_level=3"
    "udev.log_priority=3"
  ];

  # 1.5 power containment: public execution of power-profiles-daemon before tlp murders it in cold blood
  services.power-profiles-daemon.enable = false;
  
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
    };
  };

  # 2. networking: broadcasting our existential dread directly to the local subnet
  networking.hostName = "lost"; # accurate diagnostic status of the user and their root partition
  networking.networkmanager.enable = true;

  # 3. chronobiology: pretending time is real and localized to the midwest
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # 4. display manager: bloatware emergency shelter for when hyprland commits suicide on a minor release
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true; # emotional support desktop environment for wayland casualties

  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # flatpak on nixos: ideological treason, running bubblewrap containers inside a read-only store
  services.flatpak.enable = true;

  # 5. window manager: held together by uwsm and unresolved emotional trauma
  programs.hyprland = {
    enable = true;
    withUWSM = true; # systemd putting a leash on the compositor so it stops leaking zombie procs into the void
  };

  # 6. audio plumbing: pulseaudio corpse buried in an unmarked shallow grave
  services.printing.enable = true;
  services.pulseaudio.enable = false; # salt the earth where pulseaudio once stood
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };
  hardware.bluetooth.enable = true;

  # 7. user definition: ashley, who typed 'yay -s' without reading the pkgbuild and invited an ebpf rootkit to live rent-free in memory
  users.users."ashley" = {
    isNormalUser = true;
    description = "ashley";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" ];
    shell = pkgs.zsh;
    packages = with pkgs; [
      kdePackages.kate
    ];
  };

  # 8. flakes & experimental hubris: drinking the deterministic kool-aid to forget mutable state ever existed
  programs.firefox.enable = true;
  programs.zsh.enable = true;
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # 9. obs studio: virtual camera plumbing wrapped tightly so v4l2 doesn't leak into the abyss
  programs.obs-studio = {
    enable = true;
    enableVirtualCamera = true; # loops kernel modules without contaminating the functional closure
    plugins = with pkgs.obs-studio-plugins; [
      obs-pipewire-audio-capture # praying to the wireplumber daemon that audio streams actually bind
    ];
  };
  security.polkit.enable = true; # paying the security toll so systemd stops denying camera permissions out of spite

  # 9.5 portal plumbing: preventing screen share from streaming an infinite recursive void into discord
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    config.common.default = [ "hyprland" "gtk" ];
  };

  # 10. digital hoarder collection: terminal toys to look like a cinematic hacker while nix rebuilds world
  environment.systemPackages = with pkgs; [
    # wayland rice tooling
    kitty
    git
    quickshell
    matugen
    awww
    mpvpaper
    hyprpicker
    wl-clipboard
    brightnessctl
    playerctl

    # terminal cosplay to pretend we understand rust cli tooling
    micro
    neovim
    fastfetch
    eza
    zoxide
    fzf
    bat
    ripgrep
    fd
    jq
    yazi

    # glue scripts and image manipulation dependencies
    python3
    python3Packages.pillow

    # ps4 theme extraction contraband
    unar

    # identity verification for the hub
    gh
  ];

  # 11. typography: sacrificial glyphs to keep unicode tofu rectangles from infesting waybar
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];

  # touch this value and the ghost of atomic-lockfile crawls out of /nix/store to revoke your sudo privileges
  system.stateVersion = "26.05";
}
