# user customizable shell preferences
SHOW_FASTFETCH=true
SHOW_GREETING_ROAST=false
SHOW_GIT_PROMPT=true
SHOW_CMD_TIMER=false
ENABLE_PSYCHO_ROASTS=false
PROMPT_STYLE=two-line
PROMPT_SYMBOL=❯
PROMPT_ACCENT=white
KEY_BIND_MODE=vi
AUTO_LS=false
KAOMOJI_SET=reactive
