-- auto-generated by matugen — do not edit
return {
    active_border_1 = "rgba({{ colors.primary.dark.hex_stripped }}ff)",
    active_border_2 = "rgba({{ colors.secondary.dark.hex_stripped }}ff)",
    inactive_border = "rgba({{ colors.outline.dark.hex_stripped }}ff)",
}
