-- auto-generated by matugen — do not edit
return {
    bg = "{{colors.surface.default.hex}}",
    fg = "{{colors.on_surface.default.hex}}",
    primary = "{{colors.primary.default.hex}}",
    on_primary = "{{colors.on_primary.default.hex}}",
    secondary = "{{colors.secondary.default.hex}}",
    on_secondary = "{{colors.on_secondary.default.hex}}",
    tertiary = "{{colors.tertiary.default.hex}}",
    on_tertiary = "{{colors.on_tertiary.default.hex}}",
    error = "{{colors.error.default.hex}}",
    on_error = "{{colors.on_error.default.hex}}",
    outline = "{{colors.outline.default.hex}}",
    outline_variant = "{{colors.outline_variant.default.hex}}",
    surface_container = "{{colors.surface_container.default.hex}}",
    surface_container_high = "{{colors.surface_container_high.default.hex}}",
    surface_container_lowest = "{{colors.surface_container_lowest.default.hex}}",
    inverse_primary = "{{colors.inverse_primary.default.hex}}",
}
