typeset -g MATUGEN_PRIMARY="{{colors.primary.default.hex}}"
typeset -g MATUGEN_SECONDARY="{{colors.secondary.default.hex}}"
typeset -g MATUGEN_TERTIARY="{{colors.tertiary.default.hex}}"
typeset -g MATUGEN_ERROR="{{colors.error.default.hex}}"
typeset -g MATUGEN_OUTLINE="{{colors.outline.default.hex}}"
typeset -g MATUGEN_SURFACE="{{colors.surface.default.hex}}"
typeset -g MATUGEN_ON_SURFACE="{{colors.on_surface.default.hex}}"
export FZF_DEFAULT_OPTS="--color=bg+:-1,bg:-1,spinner:{{colors.primary.default.hex}},hl:{{colors.tertiary.default.hex}},fg:{{colors.on_surface.default.hex}},header:{{colors.secondary.default.hex}},info:{{colors.primary.default.hex}},pointer:{{colors.primary.default.hex}},marker:{{colors.primary.default.hex}},prompt:{{colors.secondary.default.hex}},hl+:{{colors.tertiary.default.hex}}"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg={{colors.outline.default.hex}}"